### ISSUE TITLE
关于vmq服务端问题

### ISSUE THREAD

**Issue by xeye666** [huangfengye/VmqForZfaka#5]
1、请问这个服务端是不是需要单独拿一台服务器跟域名安装？
2、是否可以直接跟zfk用同一台服务器同一个域名？
3、能不能把服务端直接集成到zfk中？

**Comment by mahaonan1005** [comment]
不需要单独服务器，可以用同一个域名，设置一个子域名就可以了，例如pay.xxx.com
zfaka和vmq是两个不同的程序啊，语言都不一样不能集成的

**Comment by huangfengye** [comment]
服务器不是我弄的。不清楚
