### ISSUE TITLE
V免签问题多挺多 作者不更新了.换个增强版兼容吧

### ISSUE THREAD

**Issue by rrkai** [huangfengye/VmqForZfaka#8]
https://github.com/dreamncn/VPay

**Comment by huangfengye** [comment]
这版本好像有问题。。。我搞不懂。。。

**Comment by rrkai** [comment]
> 这版本好像有问题。。。我搞不懂。。。

很多问题....所以我抛弃了 现在用的VPAY 问题比较少  作者说新版本要上线了

**Comment by 8ww** [comment]
@rrkai  有对接插件吗

**Comment by t-o-n-y-w** [comment]
> > 这版本好像有问题。。。我搞不懂。。。
> 
> 很多问题...所以我抛了现在用的VPAY问题比较少作者说新版本要上线了

有没有使用教程 ，我看不到 尴尬 你的联系方式 能发一下吗
